sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f ./Dockerfile.dev -t ranggarifqi/ahsan-backend-dev .

script:
  - docker run -e CGO_ENABLED=0 ranggarifqi/ahsan-backend-dev make test

# deploy:
#   provider: script
#   script: bash scripts/deploy.sh
#   on:
#     branch: main
