version: "3"

volumes:
  ahsan-name-generator-test-data:

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=ahsan_name_generator_test
    ports: 
      - 5434:5432
    volumes: 
      - ahsan-name-generator-test-data:/var/lib/postgresql/data/